name: Release
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GitHub Docker Repository
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Shallow checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: "Docker: Parse release version"
      id: docker_release_version
      run: echo ::set-output name=docker_release_version::${GITHUB_REF/refs\/tags\//}
    - name: "Build: Docker image"
      run: |
        docker build --build-arg CDN_VERSION_ARG=${{ steps.docker_release_version.outputs.docker_release_version }} \
        -t docker.pkg.github.com/$GITHUB_REPOSITORY/icon-cdn:${{ steps.docker_release_version.outputs.docker_release_version }} \
        -t docker.pkg.github.com/$GITHUB_REPOSITORY/icon-cdn:latest \
        .
    - name: "Publish: Docker image"
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/icon-cdn:${{ steps.docker_release_version.outputs.docker_release_version }}
    - name: "Publish: Docker image as latest"
      run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/icon-cdn:latest
  
  aws-s3-upload:
    runs-on: ubuntu-latest
    env:
      S3_DIR: s3-icons
      AWS_REGION: eu-central-1
      S3BUCKET: cloudfront-icon-cdn-backend-esta-web-prod
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - name: Create s3 upload directory
      run: mkdir $S3_DIR
    - name: Copy fpl icons
      run: cp -R ./icons/svg/FPL/ ./$S3_DIR/fpl
    - name: Copy kom icons
      run: cp -R ./icons/svg/KOM/responsive/ ./$S3_DIR/kom
    - name: Prepare icons
      run: node ../.github/flatten-icons.js s3
      working-directory: ${{ env.S3_DIR }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ICON_CDN_AWS_ACCESS_ID }}
        aws-secret-access-key: ${{ secrets.ICON_CDN_AWS_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Upload KOM icons to s3
      run: aws s3 cp . s3://${{ env.S3BUCKET }}/kom/ --exclude "*" --include "*.svg" --include "index.json"
      working-directory: ${{ env.S3_DIR }}/kom
    - name: Upload FPL icons to s3
      run: aws s3 cp . s3://${{ env.S3BUCKET }}/fpl/ --exclude "*" --include "*.svg" --include "index.json"
      working-directory: ${{ env.S3_DIR }}/fpl
